/*CMD
  command: /myfa-api-v2
  help: MYFA BIRR complete BB WebApp API
  need_reply: false
  auto_retry_time:
  folder: MYFA API
  answer:
  keyboard:
  aliases:
  group:
CMD*/

function respond(v){ WebApp.render({content:JSON.stringify(v),mime_type:"application/json"}); }
function N(v,d){var n=Number(v);return isFinite(n)?n:d}
function S(v,d,m){var s=String(v==null?d:v);return m&&s.length>m?s.slice(0,m):s}
function A(v){return Array.isArray(v)?v:[]}
function day(){return new Date().toISOString().slice(0,10)}
function admin(){return String(user.telegramid)===String(Bot.getProp("MYFA_ADMIN_TELEGRAM_ID",""))}
function C(){var x=Bot.getProp("MYFA_CONFIG",{});return x&&typeof x==="object"?x:{}}
function tasks(){var x=Bot.getProp("MYFA_TASKS",[]);if(!Array.isArray(x)||!x.length)x=[{id:"welcome",title:"Welcome to MYFA BIRR",description:"Open the app and claim your starter reward.",reward:100,active:true,type:"internal"},{id:"channel",title:"Join official channel",description:"Join the MYFA BIRR official Telegram channel.",reward:100,active:true,type:"telegram",url:"https://t.me/Besh_beshs"}];return x}
function campaigns(){var x=Bot.getProp("MYFA_CAMPAIGNS",[]);return Array.isArray(x)?x:[]}
function withdrawals(){var x=Bot.getProp("MYFA_WITHDRAWALS",[]);return Array.isArray(x)?x:[]}
function top(){var x=Bot.getProp("MYFA_TOP",[]);return Array.isArray(x)?x:[]}
function saveState(s){User.setProp({name:"MYFA_STATE",value:s})}
function state(){var s=User.getProp("MYFA_STATE",{});if(!s||typeof s!=="object")s={};s.points=N(s.points,0);s.realBalance=N(s.realBalance,0);s.adsWatchedToday=N(s.adsWatchedToday,0);s.totalAdsWatchedLifetime=N(s.totalAdsWatchedLifetime,0);s.referredUsers=A(s.referredUsers);s.claimedTasks=A(s.claimedTasks);s.claimedAds=A(s.claimedAds);s.claimedPromos=A(s.claimedPromos);s.withdrawals=A(s.withdrawals);s.games=s.games&&typeof s.games==="object"?s.games:{};s.settings=s.settings&&typeof s.settings==="object"?s.settings:{};return s}
function saveTop(s){var t=top(),id=String(user.telegramid),row={telegramId:id,name:S(s.accountName||s.username||user.first_name||"User","User",80),points:N(s.points,0)},found=-1;for(var i=0;i<t.length;i++)if(String(t[i].telegramId)===id){found=i;break}if(found>=0)t[found]=row;else t.push(row);t.sort(function(a,b){return N(b.points,0)-N(a.points,0)});Bot.setProp("MYFA_TOP",t.slice(0,50),"json");return t.slice(0,50)}
function ensure(s,ref){if(s.createdAt)return s;s={username:S(user.first_name||"User","User",80),accountName:S(((user.first_name||"")+" "+(user.last_name||"")).trim()||"User","User",100),points:0,realBalance:0,adsWatchedToday:0,totalAdsWatchedLifetime:0,referredBy:null,referredUsers:[],claimedTasks:[],claimedAds:[],claimedPromos:[],dailyClaimDate:null,streakCount:1,lastLoginDate:day(),createdAt:Date.now(),isBanned:false,settings:{sound:true,theme:"dark",lang:"EN"},games:{},withdrawals:[]};var r=S(ref||"","",100).replace(/^ref/i,"");if(r&&r!==String(user.telegramid)){s.referredBy=r;var rs=Bot.getProp({name:"MYFA_STATE",user_telegramid:r});if(rs&&typeof rs==="object"){rs=stateOther(rs);if(rs.referredUsers.indexOf(String(user.telegramid))<0)rs.referredUsers.push(String(user.telegramid));var rb=N(C().referralBonusReferrer,0);rs.realBalance+=rb;Bot.setProp({name:"MYFA_STATE",value:rs,user_telegramid:r});saveTop(rs);var rr=N(C().referralBonusReferee,0);s.realBalance+=rr;Api.sendMessage({chat_id:r,text:"🎉 New referral joined MYFA BIRR. You earned +"+rb+" cash."})}}Bot.setProp("MYFA_TOTAL_USERS",N(Bot.getProp("MYFA_TOTAL_USERS",0),0)+1,"integer");saveState(s);saveTop(s);return s}
function stateOther(s){s=s||{};if(!Array.isArray(s.referredUsers))s.referredUsers=[];if(!Array.isArray(s.claimedTasks))s.claimedTasks=[];if(!Array.isArray(s.claimedAds))s.claimedAds=[];if(!Array.isArray(s.claimedPromos))s.claimedPromos=[];s.realBalance=N(s.realBalance,0);s.points=N(s.points,0);return s}
function reset(s){var d=day();if(s.lastLoginDate!==d){var p=s.lastLoginDate;s.lastLoginDate=d;s.adsWatchedToday=0;s.claimedAds=[];if(p){var diff=new Date(d+"T00:00:00Z").getTime()-new Date(p+"T00:00:00Z").getTime();s.streakCount=diff<=172800000?Math.max(1,N(s.streakCount,1)+1):1}else s.streakCount=1}return s}
function safePageData(s){return {ok:true,user:Object.assign({},s,{telegramId:String(user.telegramid),id:user.id,first_name:user.first_name||"",last_name:user.last_name||"",tgUsername:user.username||"",isAdmin:admin()}),config:C(),tasks:tasks(),campaigns:campaigns().filter(function(x){return x.active!==false}),leaderboard:top()}}
var p={};try{p=typeof content==="string"?JSON.parse(content||"{}"):content||{}}catch(e){return respond({ok:false,error:"INVALID_JSON"})}
var action=S(p.action,"",50),s=reset(state());if(!s.createdAt)s=ensure(s,p.refParam||User.getProp("MYFA_PENDING_REF","")||"");if(s.isBanned&&!['bootstrap','globals','user'].includes(action)){saveState(s);return respond({ok:false,error:"ACCOUNT_BANNED"})}

if(action==="bootstrap"||action==="user"){saveState(s);saveTop(s);return respond(safePageData(s))}
if(action==="globals")return respond({ok:true,config:C(),totalUsers:N(Bot.getProp("MYFA_TOTAL_USERS",0),0),leaderboard:top()})
if(action==="save-profile"){if(p.username)s.username=S(p.username,"User",80);if(p.accountName)s.accountName=S(p.accountName,s.username,100);saveState(s);saveTop(s);return respond({ok:true,user:s})}
if(action==="save-settings"){s.settings={sound:p.sound!==false,theme:p.theme==="light"?"light":"dark",lang:String(p.lang||"EN").toUpperCase()==="AM"?"AM":"EN"};saveState(s);return respond({ok:true,user:s})}
if(action==="daily-claim"){var d=day();if(s.dailyClaimDate===d)return respond({ok:false,error:"ALREADY_CLAIMED",user:s});var base=N(C().dailyReward,50),step=N(C().streakStep,10),reward=base+Math.min(7,Math.max(1,N(s.streakCount,1)))*step;s.points+=reward;s.dailyClaimDate=d;saveState(s);saveTop(s);return respond({ok:true,reward:reward,streak:s.streakCount,user:s})}
if(action==="claim-task"){var tid=S(p.taskId,"",100),ts=tasks(),task=null;for(var i=0;i<ts.length;i++)if(String(ts[i].id)===tid&&ts[i].active!==false){task=ts[i];break}if(!task)return respond({ok:false,error:"TASK_NOT_FOUND"});if(s.claimedTasks.indexOf(tid)>=0)return respond({ok:false,error:"ALREADY_CLAIMED"});var tr=N(task.reward,0);if(tr<=0)return respond({ok:false,error:"INVALID_REWARD"});s.claimedTasks.push(tid);s.points+=tr;s.realBalance+=N(task.cashReward,0);saveState(s);saveTop(s);return respond({ok:true,reward:tr,user:s})}
if(action==="ad-open"){var aid=S(p.adId,"",100),foundAd=false;for(var ac=0;ac<campaigns().length;ac++)if(String(campaigns()[ac].id)===aid&&campaigns()[ac].active!==false){foundAd=true;break}if(!foundAd)return respond({ok:false,error:"AD_NOT_FOUND"});s.pendingAd={id:aid,startedAt:Date.now(),nonce:String(Date.now())+String(user.telegramid)};saveState(s);return respond({ok:true})}
if(action==="claim-ad"){var aid2=S(p.adId,"",100),pa=s.pendingAd||{};if(String(pa.id)!==aid2)return respond({ok:false,error:"AD_NOT_STARTED"});if(Date.now()-N(pa.startedAt,0)<5000)return respond({ok:false,error:"WATCH_MORE"});var cs=campaigns(),ad=null;for(var aj=0;aj<cs.length;aj++)if(String(cs[aj].id)===aid2&&cs[aj].active!==false){ad=cs[aj];break}if(!ad)return respond({ok:false,error:"AD_NOT_FOUND"});if(s.claimedAds.indexOf(aid2)>=0)return respond({ok:false,error:"ALREADY_CLAIMED"});if(s.adsWatchedToday>=N(C().adsDailyLimit,10))return respond({ok:false,error:"DAILY_AD_LIMIT"});var ar=N(ad.reward,0);s.claimedAds.push(aid2);s.pendingAd=null;s.adsWatchedToday++;s.totalAdsWatchedLifetime++;s.points+=ar;ad.spent=N(ad.spent,0)+ar;saveState(s);saveTop(s);Bot.setProp("MYFA_CAMPAIGNS",cs.slice(-60),"json");return respond({ok:true,reward:ar,user:s})}
if(action==="create-ad"){var title=S(p.title,"MYFA Ad",80),url=S(p.url,"",500),rw=N(p.reward,0),budget=N(p.budget,0);if(!/^https?:\/\//i.test(url)||rw<=0||budget<Math.max(100,rw*100))return respond({ok:false,error:"INVALID_AD"});if(s.realBalance<budget)return respond({ok:false,error:"INSUFFICIENT_BALANCE"});var ca=campaigns();var cid="AD-"+Date.now()+"-"+user.telegramid;var adrow={id:cid,title:title,url:url,reward:rw,budget:budget,spent:0,active:true,owner:String(user.telegramid),createdAt:Date.now()};ca.push(adrow);s.realBalance-=budget;Bot.setProp("MYFA_CAMPAIGNS",ca.slice(-60),"json");saveState(s);return respond({ok:true,campaign:adrow,user:s})}
if(action==="create-task"){if(!admin())return respond({ok:false,error:"UNAUTHORIZED"});var nt=tasks();var row={id:"TASK-"+Date.now(),title:S(p.title,"MYFA Task",100),description:S(p.description,"",300),reward:N(p.reward,0),type:S(p.type,"internal",40),url:S(p.url,"",500),active:true};nt.push(row);Bot.setProp("MYFA_TASKS",nt.slice(-80),"json");return respond({ok:true,task:row,tasks:nt})}
if(action==="tasks")return respond({ok:true,tasks:tasks()})
if(action==="campaigns")return respond({ok:true,campaigns:campaigns().filter(function(x){return x.active!==false})})
if(action==="referrals"){var refs=[];for(var ri=0;ri<s.referredUsers.length;ri++){var rr2=Bot.getProp({name:"MYFA_STATE",user_telegramid:s.referredUsers[ri]});if(rr2)refs.push({id:s.referredUsers[ri],name:rr2.accountName||rr2.username||"User",points:N(rr2.points,0)})}return respond({ok:true,count:refs.length,referrals:refs,referrer:s.referredBy||null})}
if(action==="leaderboard"){var t=top(),rank=null;for(var li=0;li<t.length;li++)if(String(t[li].telegramId)===String(user.telegramid)){rank=li+1;break}return respond({ok:true,rank:rank,rows:t})}
if(action==="game"){var g=S(p.game,"",30),key=day();s.games=s.games||{};var gs=s.games[g]||{date:key,plays:0,wins:0};if(gs.date!==key)gs={date:key,plays:0,wins:0};if(gs.plays>=N(C().gameDailyPlays,20))return respond({ok:false,error:"GAME_DAILY_LIMIT",user:s});gs.plays++;var result={},reward=0,win=false;if(g==="aviator"){var stake=N(p.stake,0),target=N(p.target,1.5);if(stake<=0||stake>s.points||target<1.01||target>20)return respond({ok:false,error:"INVALID_AVIATOR"});s.points-=stake;var crash=Number((1.05+Math.random()*4.95).toFixed(2));win=target<=crash;if(win){reward=Number((stake*target).toFixed(2));s.points+=reward;gs.wins++}result={crash:crash,target:target,stake:stake,payout:win?reward:0,win:win}}
else if(g==="drop"){var score=Math.max(0,Math.min(500,Math.floor(N(p.score,0))));reward=Math.floor(score/10);s.points+=reward;result={score:score,reward:reward}}
else if(g==="multi-ox"){var picks=["A","B","C","D","E"],pick=S(p.pick,"",2),draw=picks[Math.floor(Math.random()*picks.length)];win=pick===draw;reward=win?N(C().multiOxReward,100):0;s.points+=reward;if(win)gs.wins++;result={pick:pick,draw:draw,reward:reward,win:win}}
else if(g==="sketch"){var words=["cat","car","house","tree","phone"],answer=S(p.answer,"",20).toLowerCase(),correct=words[Math.floor(Math.random()*words.length)];win=answer===correct;reward=win?N(C().sketchReward,75):0;s.points+=reward;if(win)gs.wins++;result={answer:correct,reward:reward,win:win}}
else if(g==="daily-combo"){var sy=["💎","⭐","🔥","🍀","🎁"],combo=[sy[Math.floor(Math.random()*sy.length)],sy[Math.floor(Math.random()*sy.length)],sy[Math.floor(Math.random()*sy.length)]],chosen=A(p.combo).map(function(x){return String(x)});win=chosen.length===3&&chosen.join("")===combo.join("");reward=win?N(C().dailyComboReward,250):0;s.points+=reward;if(win)gs.wins++;result={combo:combo,reward:reward,win:win}}
else return respond({ok:false,error:"UNKNOWN_GAME"});s.games[g]=gs;saveState(s);saveTop(s);return respond({ok:true,game:g,result:result,user:s})}
if(action==="withdrawals"){var mine=withdrawals().filter(function(w){return String(w.telegramId)===String(user.telegramid)}).slice(-30).reverse();return respond({ok:true,withdrawals:mine})}
if(action==="withdraw-create"){var wa=N(p.amount,0),minw=N(C().minWithdraw,1),method=S(p.method,"unknown",50),acct=S(p.account,"",150);if(wa<minw)return respond({ok:false,error:"MINIMUM_WITHDRAWAL"});if(wa>s.realBalance)return respond({ok:false,error:"INSUFFICIENT_BALANCE"});if(!acct)return respond({ok:false,error:"ACCOUNT_REQUIRED"});var wl=withdrawals(),wid="WD-"+Date.now()+"-"+user.telegramid,wr={id:wid,telegramId:String(user.telegramid),name:s.accountName||s.username,amount:Number(wa.toFixed(2)),method:method,account:acct,status:"pending",createdAt:Date.now()};wl.push(wr);s.realBalance-=wa;s.withdrawals.unshift(wr);s.withdrawals=s.withdrawals.slice(0,20);Bot.setProp("MYFA_WITHDRAWALS",wl.slice(-100),"json");saveState(s);var aidm=Bot.getProp("MYFA_ADMIN_TELEGRAM_ID","");if(aidm)Api.sendMessage({chat_id:aidm,text:"💸 MYFA withdrawal\nID: "+wid+"\nUser: "+wr.name+"\nAmount: $"+wr.amount+"\nMethod: "+method+"\nAccount: "+acct});return respond({ok:true,withdrawal:wr,user:s})}
if(action==="promo-claim"){var code=S(p.code,"",80),pr=Bot.getProp("MYFA_PROMOS",{})||{},po=pr[code];if(!po)return respond({ok:false,error:"INVALID_PROMO"});if(s.claimedPromos.indexOf(code)>=0)return respond({ok:false,error:"PROMO_ALREADY_CLAIMED"});var pv=N(po.reward,0);s.claimedPromos.push(code);s.points+=pv;saveState(s);saveTop(s);return respond({ok:true,reward:pv,user:s})}
if(action==="admin-stats"){if(!admin())return respond({ok:false,error:"UNAUTHORIZED"});var aw=withdrawals(),pend=aw.filter(function(x){return x.status==="pending"}).length;return respond({ok:true,totalUsers:N(Bot.getProp("MYFA_TOTAL_USERS",0),0),pendingWithdrawals:pend,tasks:tasks().length,campaigns:campaigns().length,leaderboard:top()})}
if(action==="admin-withdraw"){if(!admin())return respond({ok:false,error:"UNAUTHORIZED"});var wi=S(p.id,"",100),st=S(p.status,"",20),allw=withdrawals(),targetW=null;for(var wx=0;wx<allw.length;wx++)if(String(allw[wx].id)===wi){targetW=allw[wx];break}if(!targetW)return respond({ok:false,error:"WITHDRAWAL_NOT_FOUND"});if(["approved","rejected","paid"].indexOf(st)<0)return respond({ok:false,error:"INVALID_STATUS"});targetW.status=st;targetW.reviewedAt=Date.now();Bot.setProp("MYFA_WITHDRAWALS",allw.slice(-100),"json");if(targetW.telegramId)Api.sendMessage({chat_id:targetW.telegramId,text:"💸 Withdrawal "+targetW.id+" is now "+st+"."});return respond({ok:true,withdrawal:targetW})}
if(action==="admin-ban"){if(!admin())return respond({ok:false,error:"UNAUTHORIZED"});var bid=S(p.telegramId,"",50),bs=Bot.getProp({name:"MYFA_STATE",user_telegramid:bid});if(!bs)return respond({ok:false,error:"USER_NOT_FOUND"});bs=stateOther(bs);bs.isBanned=Boolean(p.banned);Bot.setProp({name:"MYFA_STATE",value:bs,user_telegramid:bid});return respond({ok:true,telegramId:bid,banned:bs.isBanned})}
if(action==="admin-config"){if(!admin())return respond({ok:false,error:"UNAUTHORIZED"});if(!p.config||typeof p.config!=="object")return respond({ok:false,error:"INVALID_CONFIG"});Bot.setProp("MYFA_CONFIG",p.config,"json");return respond({ok:true,config:p.config})}
if(action==="admin-promo"){if(!admin())return respond({ok:false,error:"UNAUTHORIZED"});var pcs=Bot.getProp("MYFA_PROMOS",{})||{},pc=S(p.code,"",80);pcs[pc]={reward:N(p.reward,0),createdAt:Date.now()};Bot.setProp("MYFA_PROMOS",pcs,"json");return respond({ok:true,code:pc})}
return respond({ok:false,error:"UNKNOWN_ACTION",action:action});
