/*CMD
  command: /myfa-api-v2
  help: MYFA BIRR complete BB WebApp API
  need_reply: false
  auto_retry_time:
  folder: MYFA API
  answer:
  keyboard:
  aliases:
  group:
CMD*/

/*
  User-bound webhook endpoint. Never call this from a public WebApp URL directly;
  the WebApp receives the per-user webhook URL generated by /start.
*/
function respond(v){ WebApp.render({ content: JSON.stringify(v), mime_type: "application/json" }); }
function N(v,d){ var n=Number(v); return isFinite(n)?n:d; }
function S(v,d,m){ var x=String(v==null?d:v); return m&&x.length>m?x.slice(0,m):x; }
function A(v){ return Array.isArray(v)?v:[]; }
function today(){ return new Date().toISOString().slice(0,10); }
function isAdmin(){ return String(user.telegramid)===String(Bot.getProp("MYFA_ADMIN_TELEGRAM_ID","")); }
function config(){ var c=Bot.getProp("MYFA_CONFIG",{}); return c&&typeof c==="object"?c:{}; }
function clean(s){
  if(!s||typeof s!=="object")s={};
  s.points=N(s.points,0);s.realBalance=N(s.realBalance,0);s.adsWatchedToday=N(s.adsWatchedToday,0);s.totalAdsWatchedLifetime=N(s.totalAdsWatchedLifetime,0);
  s.referredUsers=A(s.referredUsers);s.claimedTasks=A(s.claimedTasks);s.claimedAds=A(s.claimedAds);s.claimedPromos=A(s.claimedPromos);s.withdrawals=A(s.withdrawals);
  s.games=s.games&&typeof s.games==="object"?s.games:{};s.settings=s.settings&&typeof s.settings==="object"?s.settings:{};s.createdAt=N(s.createdAt,0);s.isBanned=Boolean(s.isBanned);return s;
}
function getState(){ return clean(User.getProp("MYFA_STATE",{})); }
function saveState(s){ User.setProp({name:"MYFA_STATE",value:clean(s)}); }
function tasks(){ var t=Bot.getProp("MYFA_TASKS",[]); if(!Array.isArray(t)||!t.length)t=[{id:"welcome",title:"Welcome to MYFA BIRR",description:"Open the app and claim your starter reward.",reward:100,active:true,type:"internal"},{id:"channel",title:"Join official channel",description:"Join the MYFA BIRR official Telegram channel.",reward:100,active:true,type:"telegram",url:"https://t.me/Besh_beshs"}]; return t; }
function campaigns(){ var c=Bot.getProp("MYFA_CAMPAIGNS",[]); return Array.isArray(c)?c:[]; }
function withdrawals(){ var w=Bot.getProp("MYFA_WITHDRAWALS",[]); return Array.isArray(w)?w:[]; }
function top(){ var t=Bot.getProp("MYFA_TOP",[]); return Array.isArray(t)?t:[]; }
function saveTop(s){
  var t=top(),id=String(user.telegramid),row={telegramId:id,name:S(s.accountName||s.username||user.first_name||"User","User",80),points:N(s.points,0)},i;
  for(i=0;i<t.length;i++){if(String(t[i].telegramId)===id){t[i]=row;break;}}
  if(i===t.length)t.push(row);t.sort(function(a,b){return N(b.points,0)-N(a.points,0)});Bot.setProp("MYFA_TOP",t.slice(0,50),"json");return t.slice(0,50);
}
function init(s,ref){
  if(s.createdAt)return s;
  s={username:S(user.first_name||"User","User",80),accountName:S(((user.first_name||"")+" "+(user.last_name||"")).trim()||"User","User",100),points:0,realBalance:0,adsWatchedToday:0,totalAdsWatchedLifetime:0,referredBy:null,referredUsers:[],claimedTasks:[],claimedAds:[],claimedPromos:[],dailyClaimDate:null,streakCount:1,lastLoginDate:today(),createdAt:Date.now(),isBanned:false,settings:{sound:true,theme:"dark",lang:"EN"},games:{},withdrawals:[]};
  var r=S(ref||"","",100).replace(/^ref/i,"");
  if(r&&r!==String(user.telegramid)){
    s.referredBy=r;var rs=Bot.getProp({name:"MYFA_STATE",user_telegramid:r});
    if(rs&&typeof rs==="object"){
      rs=clean(rs);if(rs.referredUsers.indexOf(String(user.telegramid))<0)rs.referredUsers.push(String(user.telegramid));
      var rb=N(config().referralBonusReferrer,0);rs.realBalance+=rb;Bot.setProp({name:"MYFA_STATE",value:rs,user_telegramid:r});saveTop(rs);
      s.realBalance+=N(config().referralBonusReferee,0);Api.sendMessage({chat_id:r,text:"🎉 New referral joined MYFA BIRR. You earned +"+rb+" cash."});
    }
  }
  Bot.setProp("MYFA_TOTAL_USERS",N(Bot.getProp("MYFA_TOTAL_USERS",0),0)+1,"integer");saveState(s);saveTop(s);return s;
}
function resetDaily(s){
  var d=today();if(s.lastLoginDate!==d){var p=s.lastLoginDate;s.lastLoginDate=d;s.adsWatchedToday=0;s.claimedAds=[];if(p){var diff=new Date(d+"T00:00:00Z").getTime()-new Date(p+"T00:00:00Z").getTime();s.streakCount=diff<=172800000?Math.max(1,N(s.streakCount,1)+1):1}else s.streakCount=1;}return s;
}
var payload={};try{payload=typeof content==="string"?JSON.parse(content||"{}"):content||{}}catch(e){return respond({ok:false,error:"INVALID_JSON"});}
var action=S(payload.action,"",60),state=getState();if(!state.createdAt)state=init(state,payload.refParam||User.getProp("MYFA_PENDING_REF","")||"");state=resetDaily(state);
if(state.isBanned&&["bootstrap","user","globals"].indexOf(action)<0){saveState(state);return respond({ok:false,error:"ACCOUNT_BANNED"});}
if(action==="bootstrap"||action==="user"){saveState(state);var tt=top();var rank=null;for(var ri=0;ri<tt.length;ri++)if(String(tt[ri].telegramId)===String(user.telegramid)){rank=ri+1;break}return respond({ok:true,user:Object.assign({},state,{telegramId:String(user.telegramid),id:user.id,first_name:user.first_name||"",last_name:user.last_name||"",tgUsername:user.username||"",isAdmin:isAdmin(),rank:rank}),config:config(),tasks:tasks(),campaigns:campaigns().filter(function(x){return x.active!==false}),leaderboard:tt});}
if(action==="globals")return respond({ok:true,config:config(),totalUsers:N(Bot.getProp("MYFA_TOTAL_USERS",0),0),leaderboard:top()});
if(action==="save-profile"){if(payload.username)state.username=S(payload.username,state.username,80);if(payload.accountName)state.accountName=S(payload.accountName,state.accountName,100);saveState(state);saveTop(state);return respond({ok:true,user:state});}
if(action==="save-settings"){state.settings={sound:payload.sound!==false,theme:payload.theme==="light"?"light":"dark",lang:String(payload.lang||"EN").toUpperCase()==="AM"?"AM":"EN"};saveState(state);return respond({ok:true,user:state});}
if(action==="daily-claim"){var dc=day=today();if(state.dailyClaimDate===dc)return respond({ok:false,error:"ALREADY_CLAIMED",user:state});var reward=N(config().dailyReward,50)+Math.min(7,Math.max(1,N(state.streakCount,1)))*N(config().streakStep,10);state.points+=reward;state.dailyClaimDate=dc;saveState(state);saveTop(state);return respond({ok:true,reward:reward,streak:state.streakCount,user:state});}
if(action==="claim-task"){var tid=S(payload.taskId,"",100),ts=tasks(),task=null;for(var ti=0;ti<ts.length;ti++)if(String(ts[ti].id)===tid&&ts[ti].active!==false){task=ts[ti];break}if(!task)return respond({ok:false,error:"TASK_NOT_FOUND"});if(state.claimedTasks.indexOf(tid)>=0)return respond({ok:false,error:"ALREADY_CLAIMED"});var tr=N(task.reward,0);if(tr<=0)return respond({ok:false,error:"INVALID_REWARD"});state.claimedTasks.push(tid);state.points+=tr;state.realBalance+=N(task.cashReward,0);saveState(state);saveTop(state);return respond({ok:true,reward:tr,user:state});}
if(action==="tasks")return respond({ok:true,tasks:tasks()});
if(action==="ad-open"){var adid=S(payload.adId,"",100),ok=false,cs=campaigns();for(var ci=0;ci<cs.length;ci++)if(String(cs[ci].id)===adid&&cs[ci].active!==false){ok=true;break}if(!ok)return respond({ok:false,error:"AD_NOT_FOUND"});state.pendingAd={id:adid,startedAt:Date.now()};saveState(state);return respond({ok:true});}
if(action==="claim-ad"){var aid=S(payload.adId,"",100),pa=state.pendingAd||{};if(String(pa.id)!==aid)return respond({ok:false,error:"AD_NOT_STARTED"});if(Date.now()-N(pa.startedAt,0)<5000)return respond({ok:false,error:"WATCH_MORE"});if(state.claimedAds.indexOf(aid)>=0)return respond({ok:false,error:"ALREADY_CLAIMED"});if(state.adsWatchedToday>=N(config().adsDailyLimit,10))return respond({ok:false,error:"DAILY_AD_LIMIT"});var ar=0,cl=campaigns();for(var aj=0;aj<cl.length;aj++)if(String(cl[aj].id)===aid&&cl[aj].active!==false){ar=N(cl[aj].reward,0);break}if(ar<=0)return respond({ok:false,error:"AD_NOT_FOUND"});state.claimedAds.push(aid);state.pendingAd=null;state.adsWatchedToday++;state.totalAdsWatchedLifetime++;state.points+=ar;saveState(state);saveTop(state);return respond({ok:true,reward:ar,user:state});}
if(action==="create-ad"){var title=S(payload.title,"MYFA Ad",80),url=S(payload.url,"",500),aw=N(payload.reward,0),budget=N(payload.budget,0);if(!/^https?:\\/\\//i.test(url)||aw<=0||budget<aw*100)return respond({ok:false,error:"INVALID_AD"});if(state.realBalance<budget)return respond({ok:false,error:"INSUFFICIENT_BALANCE"});var ca=campaigns(),cid="AD-"+Date.now()+"-"+user.telegramid,row={id:cid,title:title,url:url,reward:aw,budget:budget,spent:0,active:true,owner:String(user.telegramid),createdAt:Date.now()};ca.push(row);state.realBalance-=budget;Bot.setProp("MYFA_CAMPAIGNS",ca.slice(-60),"json");saveState(state);return respond({ok:true,campaign:row,user:state});}
if(action==="create-task"){if(!isAdmin())return respond({ok:false,error:"UNAUTHORIZED"});var nt=tasks(),nr={id:"TASK-"+Date.now(),title:S(payload.title,"MYFA Task",100),description:S(payload.description,"",300),reward:N(payload.reward,0),type:S(payload.type,"internal",40),url:S(payload.url,"",500),active:true};nt.push(nr);Bot.setProp("MYFA_TASKS",nt.slice(-80),"json");return respond({ok:true,task:nr,tasks:nt});}
if(action==="referrals"){var refs=[];for(var r=0;r<state.referredUsers.length;r++){var rr=Bot.getProp({name:"MYFA_STATE",user_telegramid:state.referredUsers[r]});if(rr)refs.push({id:state.referredUsers[r],name:rr.accountName||rr.username||"User",points:N(rr.points,0)})}return respond({ok:true,count:refs.length,referrals:refs,referrer:state.referredBy||null});}
if(action==="leaderboard"){var lb=top(),ur=null;for(var l=0;l<lb.length;l++)if(String(lb[l].telegramId)===String(user.telegramid)){ur=l+1;break}return respond({ok:true,rank:ur,rows:lb});}
if(action==="game"){var game=S(payload.game,"",30),key=today();state.games=state.games||{};var gs=state.games[game]||{date:key,plays:0,wins:0};if(gs.date!==key)gs={date:key,plays:0,wins:0};if(gs.plays>=N(config().gameDailyPlays,20))return respond({ok:false,error:"GAME_DAILY_LIMIT",user:state});gs.plays++;var result={},gr=0,won=false;if(game==="aviator"){var stake=N(payload.stake,0),target=N(payload.target,1.5);if(stake<=0||stake>state.points||target<1.01||target>20)return respond({ok:false,error:"INVALID_AVIATOR"});state.points-=stake;var crash=Number((1.05+Math.random()*4.95).toFixed(2));won=target<=crash;if(won){gr=Number((stake*target).toFixed(2));state.points+=gr;gs.wins++}result={crash:crash,target:target,stake:stake,payout:won?gr:0,win:won};}else if(game==="drop"){var score=Math.max(0,Math.min(500,Math.floor(N(payload.score,0))));gr=Math.floor(score/10);state.points+=gr;result={score:score,reward:gr};}else if(game==="multi-ox"){var picks=["A","B","C","D","E"],pick=S(payload.pick,"",2),draw=picks[Math.floor(Math.random()*picks.length)];won=pick===draw;gr=won?N(config().multiOxReward,100):0;state.points+=gr;if(won)gs.wins++;result={pick:pick,draw:draw,reward:gr,win:won};}else if(game==="sketch"){var words=["cat","car","house","tree","phone"],ans=S(payload.answer,"",30).toLowerCase(),correct=words[Math.floor(Math.random()*words.length)];won=ans===correct;gr=won?N(config().sketchReward,75):0;state.points+=gr;if(won)gs.wins++;result={answer:correct,reward:gr,win:won};}else if(game==="daily-combo"){var sy=["💎","⭐","🔥","🍀","🎁"],combo=[sy[Math.floor(Math.random()*5)],sy[Math.floor(Math.random()*5)],sy[Math.floor(Math.random()*5)]],chosen=A(payload.combo).map(function(x){return String(x)});won=chosen.length===3&&chosen.join("")===combo.join("");gr=won?N(config().dailyComboReward,250):0;state.points+=gr;if(won)gs.wins++;result={combo:combo,reward:gr,win:won};}else return respond({ok:false,error:"UNKNOWN_GAME"});state.games[game]=gs;saveState(state);saveTop(state);return respond({ok:true,game:game,result:result,user:state});}
if(action==="withdrawals"){var mine=withdrawals().filter(function(w){return String(w.telegramId)===String(user.telegramid)}).slice(-30).reverse();return respond({ok:true,withdrawals:mine});}
if(action==="withdraw-create"){var amount=N(payload.amount,0),minw=N(config().minWithdraw,1),method=S(payload.method,"unknown",50),acct=S(payload.account,"",150);if(amount<minw)return respond({ok:false,error:"MINIMUM_WITHDRAWAL"});if(amount>state.realBalance)return respond({ok:false,error:"INSUFFICIENT_BALANCE"});if(!acct)return respond({ok:false,error:"ACCOUNT_REQUIRED"});var wl=withdrawals(),wid="WD-"+Date.now()+"-"+user.telegramid,wr={id:wid,telegramId:String(user.telegramid),name:state.accountName||state.username,amount:Number(amount.toFixed(2)),method:method,account:acct,status:"pending",createdAt:Date.now()};wl.push(wr);state.realBalance-=amount;state.withdrawals.unshift(wr);state.withdrawals=state.withdrawals.slice(0,20);Bot.setProp("MYFA_WITHDRAWALS",wl.slice(-100),"json");saveState(state);var aid=Bot.getProp("MYFA_ADMIN_TELEGRAM_ID","");if(aid)Api.sendMessage({chat_id:aid,text:"💸 MYFA withdrawal\nID: "+wid+"\nUser: "+wr.name+"\nAmount: $"+wr.amount+"\nMethod: "+method+"\nAccount: "+acct});return respond({ok:true,withdrawal:wr,user:state});}
if(action==="promo-claim"){var code=S(payload.code,"",80),promos=Bot.getProp("MYFA_PROMOS",{})||{},promo=promos[code];if(!promo)return respond({ok:false,error:"INVALID_PROMO"});if(state.claimedPromos.indexOf(code)>=0)return respond({ok:false,error:"PROMO_ALREADY_CLAIMED"});var pv=N(promo.reward,0);if(pv<=0)return respond({ok:false,error:"INVALID_PROMO"});state.claimedPromos.push(code);state.points+=pv;saveState(state);saveTop(state);return respond({ok:true,reward:pv,user:state});}
if(action==="admin-stats"){if(!isAdmin())return respond({ok:false,error:"UNAUTHORIZED"});var wd=withdrawals(),pending=wd.filter(function(w){return w.status==="pending"}).length;return respond({ok:true,totalUsers:N(Bot.getProp("MYFA_TOTAL_USERS",0),0),pendingWithdrawals:pending,tasks:tasks().length,campaigns:campaigns().length,leaderboard:top()});}
if(action==="admin-withdraw"){if(!isAdmin())return respond({ok:false,error:"UNAUTHORIZED"});var wid2=S(payload.id,"",100),status=S(payload.status,"",20),all=withdrawals(),targetW=null;for(var wi=0;wi<all.length;wi++)if(String(all[wi].id)===wid2){targetW=all[wi];break}if(!targetW)return respond({ok:false,error:"WITHDRAWAL_NOT_FOUND"});if(["approved","rejected","paid"].indexOf(status)<0)return respond({ok:false,error:"INVALID_STATUS"});targetW.status=status;targetW.reviewedAt=Date.now();if(status==="rejected"){var owner=Bot.getProp({name:"MYFA_STATE",user_telegramid:targetW.telegramId});if(owner){owner=clean(owner);owner.realBalance+=N(targetW.amount,0);owner.withdrawals=A(owner.withdrawals);for(var oi=0;oi<owner.withdrawals.length;oi++)if(String(owner.withdrawals[oi].id)===wid2){owner.withdrawals[oi].status="rejected"}Bot.setProp({name:"MYFA_STATE",value:owner,user_telegramid:targetW.telegramId});}}Bot.setProp("MYFA_WITHDRAWALS",all.slice(-100),"json");if(targetW.telegramId)Api.sendMessage({chat_id:targetW.telegramId,text:"💸 Withdrawal "+targetW.id+" is now "+status+"."});return respond({ok:true,withdrawal:targetW});}
if(action==="admin-ban"){if(!isAdmin())return respond({ok:false,error:"UNAUTHORIZED"});var bid=S(payload.telegramId,"",50),bs=Bot.getProp({name:"MYFA_STATE",user_telegramid:bid});if(!bs)return respond({ok:false,error:"USER_NOT_FOUND"});bs=clean(bs);bs.isBanned=Boolean(payload.banned);Bot.setProp({name:"MYFA_STATE",value:bs,user_telegramid:bid});return respond({ok:true,telegramId:bid,banned:bs.isBanned});}
if(action==="admin-config"){if(!isAdmin())return respond({ok:false,error:"UNAUTHORIZED"});if(!payload.config||typeof payload.config!=="object")return respond({ok:false,error:"INVALID_CONFIG"});Bot.setProp("MYFA_CONFIG",payload.config,"json");return respond({ok:true,config:payload.config});}
if(action==="admin-promo"){if(!isAdmin())return respond({ok:false,error:"UNAUTHORIZED"});var code2=S(payload.code,"",80),pm=Bot.getProp("MYFA_PROMOS",{})||{};if(!code2||N(payload.reward,0)<=0)return respond({ok:false,error:"INVALID_PROMO"});pm[code2]={reward:N(payload.reward,0),createdAt:Date.now()};Bot.setProp("MYFA_PROMOS",pm,"json");return respond({ok:true,code:code2});}
return respond({ok:false,error:"UNKNOWN_ACTION",action:action});
