/*CMD
  command: script.final.js
  help: MYFA BIRR complete BB frontend
  need_reply:
  auto_retry_time:
  folder: MYFA WEBAPP
  answer:
  keyboard:
  aliases:
  group:
CMD*/
(function(){
'use strict';
const tg=window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;
const CONFIG=window.MYFA_CONFIG||{};
const API=CONFIG.apiUrl||'';
const GAMEAPI=CONFIG.gameApiUrl||'';
const APP={user:null,config:{},tasks:[],campaigns:[],leaderboard:[],page:'home',combo:[]};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>Number(v||0).toFixed(2);
const today=()=>new Date().toISOString().slice(0,10);
function toast(v){const e=$('#toast');if(!e)return;e.textContent=v;e.classList.add('show');clearTimeout(window.__myfaToast);window.__myfaToast=setTimeout(()=>e.classList.remove('show'),2400)}
async function request(url,action,data){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({action:action,refParam:CONFIG.ref||''},data||{}))});if(!r.ok)throw new Error('Backend HTTP '+r.status);const d=await r.json();if(!d.ok)throw new Error(d.error||'Request failed');return d}
async function api(action,data){return request(API,action,data)}
async function gameApi(action,data){return request(GAMEAPI,action,data)}
function card(html){return '<section class="card glass">'+html+'</section>'}
function setHeader(){const u=APP.user||{};$('#name').textContent=u.accountName||u.username||'User';$('#status').textContent=u.isAdmin?'Admin':u.isVip?'VIP Member':'Member';$('#points').textContent=Math.floor(Number(u.points||0)).toLocaleString();$('#cash').textContent=money(u.realBalance);const f='https://ui-avatars.com/api/?name='+encodeURIComponent(u.accountName||u.username||'User')+'&background=00A8FF&color=fff';$('#avatar').src=u.avatarUrl||(tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user&&tg.initDataUnsafe.user.photo_url)||f}
function nav(page){APP.page=page;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));render();window.scrollTo(0,0)}
function home(){const u=APP.user||{};const claimed=u.dailyClaimDate===today();const streak=Math.max(1,Number(u.streakCount||1));return '<div class="hero"><h1>MYFA BIRR 💎</h1><p>Earn from verified app actions, tasks, ads, games and referrals.</p><button class="btn gold" onclick="claimDaily()" '+(claimed?'disabled':'')+'>'+(claimed?'✅ Daily reward claimed':'🎁 Claim daily reward')+'</button></div>'+card('<div class="section-title"><h2>7-Day Streak</h2><span class="pill">Day '+Math.min(7,streak)+'</span></div><div class="grid grid3">'+[1,2,3,4,5,6,7].map(d=>'<div class="tag" style="text-align:center"><b>'+d+'</b><br><span>'+d*50+' 💎</span><br><small class="'+(d<=streak?'ok':'muted')+'">'+(d<=streak?'Claimed':'Locked')+'</small></div>').join('')+'</div>')+'<div class="grid">'+card('<div class="stat">'+Math.floor(u.points||0).toLocaleString()+'</div><div class="muted">Gems</div>')+card('<div class="stat">$'+money(u.realBalance)+'</div><div class="muted">Cash</div>')+card('<div class="stat">'+(u.referredUsers||[]).length+'</div><div class="muted">Referrals</div>')+card('<div class="stat">'+(u.totalAdsWatchedLifetime||0)+'</div><div class="muted">Lifetime Ads</div>')+'</div>'+card('<div class="section-title"><h2>Quick Earn</h2><span class="pill">LIVE</span></div><div class="grid"><button class="btn" onclick="nav(\'tasks\')">✅ Tasks</button><button class="btn" onclick="nav(\'games\')">🎮 Games</button><button class="btn" onclick="nav(\'withdraw\')">💸 Withdraw</button><button class="btn" onclick="nav(\'more\')">👥 Invite</button></div>')+leaderboardCard()}
function leaderboardCard(){return card('<div class="section-title"><h2>Leaderboard</h2><span class="muted">Top 50</span></div>'+APP.leaderboard.slice(0,10).map((x,i)=>'<div class="list-item"><span>#'+(i+1)+' '+esc(x.name)+'</span><b>'+Math.floor(x.points||0).toLocaleString()+' 💎</b></div>').join('')||'<div class="muted">No leaderboard yet.</div>')}
function tasksPage(){return '<div class="section-title"><h2>Tasks</h2><span class="pill">'+APP.tasks.length+'</span></div>'+APP.tasks.filter(t=>t.active!==false).map(t=>{const done=(APP.user.claimedTasks||[]).includes(String(t.id));return card('<div class="section-title"><h3>'+esc(t.title)+'</h3><span class="pill">+'+Number(t.reward||0)+' 💎</span></div><p class="muted">'+esc(t.description||'Complete this task.')+'</p>'+(t.url?'<button class="btn dark" onclick="openUrl(\''+esc(t.url)+'\')">Open Task</button>':'')+'<button class="btn green" onclick="claimTask(\''+esc(t.id)+'\')" '+(done?'disabled':'')+'>'+(done?'✅ Claimed':'Claim Reward')+'</button>')}).join('')||card('<div class="muted">No active tasks.</div>')}
function gamesPage(){return '<div class="section-title"><h2>Games</h2><span class="pill">7 games</span></div>'+card('<h3>✈️ Aviator</h3><p class="muted">Server-generated crash point. Stake gems and choose your target.</p><input id="aviStake" class="field" type="number" min="1" value="10"><input id="aviTarget" class="field" type="number" min="1.01" step="0.01" value="1.50"><button class="btn" onclick="playAviator()">Fly & Cash Out</button>')+card('<h3>💎 Drop</h3><p class="muted">Tap gems and avoid bombs for 10 seconds.</p><div id="dropBoard" class="game-board"><div id="dropScore" class="big-number">0</div></div><button class="btn green" onclick="startDropGame()">Start Drop</button>')+card('<h3>🐂 Multi Ox</h3><p class="muted">Pick one ox.</p><div class="grid grid3">'+['A','B','C','D','E'].map(x=>'<button class="btn" onclick="playOx(\''+x+'\')">Ox '+x+'</button>').join('')+'</div>')+card('<h3>✏️ Sketch Guess</h3><p class="muted">Choose your guess.</p><div class="grid">'+['cat','car','house','tree','phone'].map(x=>'<button class="btn dark" onclick="playSketch(\''+x+'\')">'+x+'</button>').join('')+'</div>')+card('<h3>🎯 Daily Combo</h3><p class="muted">Select exactly 3 symbols.</p><div id="comboPick" class="grid grid3">'+['💎','⭐','🔥','🍀','🎁'].map(x=>'<button class="btn dark" data-combo="'+x+'" onclick="toggleCombo(this,\''+x+'\')">'+x+'</button>').join('')+'</div><button class="btn gold" onclick="playCombo()">Try Combo</button>')+card('<h3>🎲 Ludo</h3><p class="muted">Wager cash and roll. Six wins 2×.</p><input id="ludoWager" class="field" type="number" min="0.01" value="0.10"><button class="btn" onclick="playLudo()">Roll Dice</button>')+card('<h3>🐔 Chicken Road</h3><p class="muted">Start a server-controlled round, advance lanes, or cash out before the death lane.</p><input id="chickenWager" class="field" type="number" min="0.01" value="0.10"><div id="chickenState" class="tag">No active round</div><div class="grid"><button class="btn" onclick="startChicken()">Start</button><button class="btn green" onclick="cashoutChicken()">Cash Out</button></div>')}
function withdrawPage(){return '<div class="section-title"><h2>Withdraw</h2><span class="pill">$'+money(APP.user.realBalance)+'</span></div>'+card('<p class="muted">Minimum withdrawal: $'+money(APP.config.minWithdraw||1)+'</p><input id="wdAmount" class="field" type="number" min="0.01" step="0.01" placeholder="Amount"><select id="wdMethod" class="field"><option>Telebirr</option><option>CBE Birr</option><option>Bank</option><option>Crypto</option></select><input id="wdAccount" class="field" placeholder="Account / wallet"><button class="btn green" onclick="submitWithdrawal()">Submit Withdrawal</button>')+card('<div class="section-title"><h3>My Requests</h3><button class="btn dark" style="width:auto" onclick="loadWithdrawals()">Refresh</button></div><div id="withdrawList"><div class="muted">Loading...</div></div>')}
function morePage(){const u=APP.user||{};const ref='https://t.me/MYFA_BIRR_BOT?start=ref'+(u.telegramId||tg?.initDataUnsafe?.user?.id||'');return '<div class="section-title"><h2>More</h2><span class="pill">MYFA</span></div>'+card('<h3>👥 Invite & Earn</h3><p class="muted">Your referral link is unique to this Telegram account.</p><input id="refLink" class="field" readonly value="'+esc(ref)+'"><button class="btn" onclick="copyReferral()">Copy Link</button>')+card('<h3>📺 Sponsored Ads</h3><p class="muted">Daily limit: '+Number(APP.config.adsDailyLimit||10)+'</p>'+APP.campaigns.slice(0,15).map(a=>'<div class="list-item"><span>'+esc(a.title)+'<br><small class="muted">+'+Number(a.reward||0)+' 💎</small></span><button class="btn green" style="width:auto" onclick="watchAd(\''+esc(a.id)+'\',\''+esc(a.url)+'\')">Watch</button></div>').join('')||'<div class="muted">No sponsored ads available.</div>')+card('<h3>🎟 Promo</h3><input id="promoCode" class="field" placeholder="Promo code"><button class="btn gold" onclick="claimPromo()">Claim Promo</button>')+card('<h3>📢 Create Ad</h3><p class="muted">Create a sponsored campaign using your cash balance.</p><input id="adTitle" class="field" placeholder="Title"><input id="adUrl" class="field" placeholder="https://example.com"><input id="adReward" class="field" type="number" placeholder="Reward gems"><input id="adBudget" class="field" type="number" placeholder="Budget"><button class="btn" onclick="createAd()">Create Campaign</button>')+card('<h3>⚙️ Settings</h3><select id="lang" class="field"><option value="EN">English</option><option value="AM">አማርኛ</option></select><select id="theme" class="field"><option value="dark">Dark</option><option value="light">Light</option></select><button class="btn" onclick="saveSettings()">Save Settings</button>')+card('<h3>🔐 Profile & Security</h3><div class="list-item"><span>Telegram ID</span><b>'+esc(u.telegramId||'')+'</b></div><div class="list-item"><span>Account</span><b>'+esc(u.accountName||u.username||'User')+'</b></div><div class="list-item"><span>Status</span><b>'+esc(u.isAdmin?'Admin':u.isVip?'VIP':'Member')+'</b></div>')+card('<h3>❓ How to Earn</h3><p class="muted">Complete tasks, watch eligible ads, play games within limits, invite friends, and request withdrawal when your cash balance meets the configured minimum. Rewards are recorded by the BB backend.</p><button class="btn dark" onclick="openOfficial()">Open Official Channel</button>')+(u.isAdmin?adminPanel():'')}
function adminPanel(){return card('<h3>🛠 Admin Center</h3><input id="adminUid" class="field" placeholder="Telegram ID"><div class="grid"><button class="btn red" onclick="banUser(true)">Ban</button><button class="btn dark" onclick="banUser(false)">Unban</button></div><input id="adminWd" class="field" placeholder="Withdrawal ID"><select id="adminStatus" class="field"><option>approved</option><option>rejected</option><option>paid</option></select><button class="btn gold" onclick="reviewWithdrawal()">Review Withdrawal</button><input id="taskTitle" class="field" placeholder="Task title"><input id="taskDesc" class="field" placeholder="Description"><input id="taskReward" class="field" type="number" placeholder="Reward gems"><input id="taskUrl" class="field" placeholder="URL"><button class="btn" onclick="createTaskAdmin()">Create Task</button><input id="promoCodeAdmin" class="field" placeholder="Promo code"><input id="promoRewardAdmin" class="field" type="number" placeholder="Reward"><button class="btn green" onclick="createPromoAdmin()">Create Promo</button><button class="btn dark" onclick="loadAdminStats()">Admin Stats</button><div id="adminStats" class="muted"></div>')}
function render(){if(!APP.user)return;let c=$('#content');if(APP.page==='home')c.innerHTML=home();else if(APP.page==='tasks')c.innerHTML=tasksPage();else if(APP.page==='games')c.innerHTML=gamesPage();else if(APP.page==='withdraw')c.innerHTML=withdrawPage();else c.innerHTML=morePage();setHeader();if(APP.page==='withdraw')setTimeout(loadWithdrawals,0);if(APP.page==='games'){APP.combo=[]}}
async function boot(){try{if(tg){tg.ready();tg.expand();try{tg.setHeaderColor('#0a0a1f');tg.setBackgroundColor('#090b18')}catch(e){}}const d=await api('bootstrap');APP.user=d.user;APP.config=d.config||{};APP.tasks=d.tasks||[];APP.campaigns=d.campaigns||[];APP.leaderboard=d.leaderboard||[];if(APP.config.maintenanceMode){$('#content').innerHTML=card('<h2>MYFA BIRR Maintenance</h2><p class="muted">Please try again later.</p>');return}render()}catch(e){console.error(e);$('#content').innerHTML=card('<h2>MYFA BIRR</h2><p class="bad">'+esc(e.message)+'</p><button class="btn" onclick="location.reload()">Reload</button>')}}
async function refresh(){const d=await api('bootstrap');APP.user=d.user;APP.config=d.config||{};APP.tasks=d.tasks||[];APP.campaigns=d.campaigns||[];APP.leaderboard=d.leaderboard||[];render()}
async function claimDaily(){try{const d=await api('daily-claim');APP.user=d.user;toast('Daily reward +'+d.reward+' 💎');render()}catch(e){toast(e.message)}}
async function claimTask(id){try{const d=await api('claim-task',{taskId:id});APP.user=d.user;toast('Task reward +'+d.reward+' 💎');render()}catch(e){toast(e.message)}}
async function watchAd(id,url){try{await api('ad-open',{adId:id});if(url)openUrl(url);toast('Ad opened. Keep it open for 5 seconds.');setTimeout(async()=>{try{const d=await api('claim-ad',{adId:id});APP.user=d.user;toast('Ad reward +'+d.reward+' 💎');render()}catch(e){toast(e.message)}},5200)}catch(e){toast(e.message)}}
let dropTimer=null,dropScore=0;function startDropGame(){clearInterval(dropTimer);dropScore=0;const board=$('#dropBoard'),score=$('#dropScore');if(!board)return;score.textContent='0';const end=Date.now()+10000;dropTimer=setInterval(()=>{if(Date.now()>=end){clearInterval(dropTimer);api('game',{game:'drop',score:dropScore}).then(d=>{APP.user=d.user;toast('Drop reward +'+d.result.reward+' 💎');render()}).catch(e=>toast(e.message));return}const x=document.createElement('div');x.className='falling';x.textContent=Math.random()<.16?'💣':'💎';x.style.left=(10+Math.random()*80)+'%';x.style.top=(15+Math.random()*70)+'%';x.onclick=()=>{dropScore=x.textContent==='💣'?Math.max(0,dropScore-20):dropScore+10;score.textContent=dropScore;x.remove()};board.appendChild(x);setTimeout(()=>x.remove(),550)},350)}
async function playAviator(){try{const d=await api('game',{game:'aviator',stake:Number($('#aviStake').value),target:Number($('#aviTarget').value)});APP.user=d.user;toast(d.result.win?'🎉 Won '+d.result.payout+' 💎':'💥 Crash at '+d.result.crash+'x');render()}catch(e){toast(e.message)}}
async function playOx(x){try{const d=await api('game',{game:'multi-ox',pick:x});APP.user=d.user;toast(d.result.win?'🐂 Winner +'+d.result.reward+' 💎':'Result: Ox '+d.result.draw);render()}catch(e){toast(e.message)}}
async function playSketch(x){try{const d=await api('game',{game:'sketch',answer:x});APP.user=d.user;toast(d.result.win?'✏️ Correct +'+d.result.reward+' 💎':'Answer: '+d.result.answer);render()}catch(e){toast(e.message)}}
function toggleCombo(el,s){if(el.classList.contains('active')){el.classList.remove('active');APP.combo=APP.combo.filter(x=>x!==s)}else if(APP.combo.length<3){el.classList.add('active');APP.combo.push(s)}}
async function playCombo(){try{if(APP.combo.length!==3)return toast('Select 3 symbols');const d=await api('game',{game:'daily-combo',combo:APP.combo});APP.user=d.user;toast(d.result.win?'🎯 Combo win +'+d.result.reward+' 💎':'Combo: '+d.result.combo.join(' '));APP.combo=[];render()}catch(e){toast(e.message)}}
async function playLudo(){try{const d=await gameApi('ludo-play',{wager:Number($('#ludoWager').value)});APP.user=d.user;toast(d.win?'🎲 Six! +$'+money(d.payout):'🎲 Roll '+d.roll+' · wager lost');render()}catch(e){toast(e.message)}}
async function startChicken(){try{const d=await gameApi('chicken-start',{wager:Number($('#chickenWager').value)});APP.user.realBalance=d.balance;APP.user=Object.assign(APP.user,{realBalance:d.balance});const e=$('#chickenState');if(e)e.textContent='Active · death lane '+d.deathLane+' · Lane 0';window.__chickenRound=d;toast('🐔 Round started');}catch(e){toast(e.message)}}
async function cashoutChicken(){try{if(!window.__chickenRound)return toast('Start a Chicken Road round');const next=Number(window.__chickenRound.lane||0)+1;const d=await gameApi('chicken-cashout',{lane:next});APP.user=d.user;window.__chickenRound=null;toast('🐔 Cash out '+d.multiplier+'x = $'+money(d.payout));render()}catch(e){toast(e.message)}}
async function submitWithdrawal(){try{const d=await api('withdraw-create',{amount:Number($('#wdAmount').value),method:$('#wdMethod').value,account:$('#wdAccount').value});APP.user=d.user;toast('Withdrawal submitted');render()}catch(e){toast(e.message)}}
async function loadWithdrawals(){try{const d=await api('withdrawals');const e=$('#withdrawList');if(!e)return;e.innerHTML=d.withdrawals.map(w=>'<div class="list-item"><span>'+esc(w.method)+'<br><small class="muted">'+esc(w.id)+'</small></span><b>$'+money(w.amount)+' · '+esc(w.status)+'</b></div>').join('')||'<div class="muted">No requests.</div>'}catch(e){toast(e.message)}}
async function claimPromo(){try{const d=await api('promo-claim',{code:$('#promoCode').value});APP.user=d.user;toast('Promo +'+d.reward+' 💎');render()}catch(e){toast(e.message)}}
async function createAd(){try{const d=await api('create-ad',{title:$('#adTitle').value,url:$('#adUrl').value,reward:Number($('#adReward').value),budget:Number($('#adBudget').value)});APP.user=d.user;toast('Campaign created');await refresh()}catch(e){toast(e.message)}}
async function saveSettings(){try{const d=await api('save-settings',{lang:$('#lang').value,theme:$('#theme').value,sound:true});APP.user=d.user;document.body.classList.toggle('light',$('#theme').value==='light');toast('Settings saved')}catch(e){toast(e.message)}}
function copyReferral(){const e=$('#refLink');navigator.clipboard?.writeText(e.value);toast('Referral link copied')}
function openUrl(url){if(url)window.open(url,'_blank','noopener,noreferrer')}
function openOfficial(){openUrl(APP.config.officialChannel||'https://t.me/Besh_beshs')}
async function banUser(b){try{await api('admin-ban',{telegramId:$('#adminUid').value,banned:b});toast(b?'User banned':'User unbanned')}catch(e){toast(e.message)}}
async function reviewWithdrawal(){try{const d=await api('admin-withdraw',{id:$('#adminWd').value,status:$('#adminStatus').value});toast('Withdrawal '+d.withdrawal.status)}catch(e){toast(e.message)}}
async function createTaskAdmin(){try{const d=await api('create-task',{title:$('#taskTitle').value,description:$('#taskDesc').value,reward:Number($('#taskReward').value),url:$('#taskUrl').value});APP.tasks=d.tasks||APP.tasks;toast('Task created');render()}catch(e){toast(e.message)}}
async function createPromoAdmin(){try{const d=await api('admin-promo',{code:$('#promoCodeAdmin').value,reward:Number($('#promoRewardAdmin').value)});toast('Promo '+d.code+' created')}catch(e){toast(e.message)}}
async function loadAdminStats(){try{const d=await api('admin-stats');$('#adminStats').textContent='Users: '+d.totalUsers+' · Pending: '+d.pendingWithdrawals+' · Tasks: '+d.tasks+' · Campaigns: '+d.campaigns}catch(e){toast(e.message)}}
window.nav=nav;window.claimDaily=claimDaily;window.claimTask=claimTask;window.watchAd=watchAd;window.startDropGame=startDropGame;window.playAviator=playAviator;window.playOx=playOx;window.playSketch=playSketch;window.toggleCombo=toggleCombo;window.playCombo=playCombo;window.playLudo=playLudo;window.startChicken=startChicken;window.cashoutChicken=cashoutChicken;window.submitWithdrawal=submitWithdrawal;window.loadWithdrawals=loadWithdrawals;window.claimPromo=claimPromo;window.createAd=createAd;window.saveSettings=saveSettings;window.copyReferral=copyReferral;window.openUrl=openUrl;window.openOfficial=openOfficial;window.banUser=banUser;window.reviewWithdrawal=reviewWithdrawal;window.createTaskAdmin=createTaskAdmin;window.createPromoAdmin=createPromoAdmin;window.loadAdminStats=loadAdminStats;window.closeModal=()=>$('#modal')?.classList.add('hidden');
document.addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(b)nav(b.dataset.nav)});
boot();
})();
