/*CMD
  command: script.bb.js
  help: MYFA BIRR BB WebApp application logic
  need_reply:
  auto_retry_time:
  folder: MYFA WEBAPP
  answer:
  keyboard:
  aliases:
  group:
CMD*/
const tg=window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;
const API=(window.MYFA_CONFIG&&window.MYFA_CONFIG.apiUrl)||'';
let MYFA={user:null,config:{},tasks:[],campaigns:[],leaderboard:[],page:'home',combo:[]};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const cash=v=>Number(v||0).toFixed(2);
function toast(s){const x=$('#toast');if(!x)return;x.textContent=s;x.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>x.classList.remove('show'),2400)}
async function call(action,data={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({action:action,refParam:window.MYFA_CONFIG?.ref||''},data))});if(!r.ok)throw new Error('Backend HTTP '+r.status);const d=await r.json();if(!d.ok)throw new Error(d.error||'Request failed');return d}
function setHeader(){const u=MYFA.user||{};$('#name').textContent=u.accountName||u.username||'User';$('#status').textContent=u.isAdmin?'Admin':(u.isVip?'VIP Member':'Member');$('#points').textContent=Math.floor(Number(u.points||0)).toLocaleString();$('#cash').textContent=cash(u.realBalance);const f='https://ui-avatars.com/api/?name='+encodeURIComponent(u.accountName||u.username||'User')+'&background=00A8FF&color=fff';$('#avatar').src=u.avatarUrl||(tg?.initDataUnsafe?.user?.photo_url)||f}
function card(h){return '<section class="card glass">'+h+'</section>'}
function nav(p){MYFA.page=p;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===p));render();window.scrollTo(0,0)}
function home(){const u=MYFA.user||{};const claimed=u.dailyClaimDate===new Date().toISOString().slice(0,10);return `<div class="hero"><h1>MYFA BIRR 💎</h1><p>Earn gems from tasks, ads, games and referrals.</p><button class="btn gold" onclick="claimDaily()" ${claimed?'disabled':''}>${claimed?'✅ Daily claimed':'🎁 Claim daily reward'}</button></div><div class="grid">${card(`<div class="stat">${Math.floor(u.points||0).toLocaleString()}</div><div class="muted">Gems</div>`)}${card(`<div class="stat">$${cash(u.realBalance)}</div><div class="muted">Cash</div>`)}${card(`<div class="stat">${(u.referredUsers||[]).length}</div><div class="muted">Referrals</div>`)}${card(`<div class="stat">${u.adsWatchedToday||0}</div><div class="muted">Ads today</div>`)}</div>${card(`<div class="section-title"><h2>Quick Actions</h2><span class="pill">BB</span></div><div class="grid"><button class="btn" onclick="nav('tasks')">✅ Tasks</button><button class="btn" onclick="nav('games')">🎮 Games</button><button class="btn" onclick="nav('withdraw')">💸 Withdraw</button><button class="btn" onclick="nav('more')">👥 Invite</button></div>`)}${leaderMini()}`}
function leaderMini(){return card(`<div class="section-title"><h2>Top Earners</h2><span class="muted">50 max</span></div>${MYFA.leaderboard.slice(0,10).map((x,i)=>`<div class="list-item"><span>#${i+1} ${esc(x.name)}</span><b>${Math.floor(x.points||0).toLocaleString()} 💎</b></div>`).join('')||'<div class="muted">No scores yet.</div>'}`)}
function tasksPage(){return `<div class="section-title"><h2>Tasks</h2><span class="pill">${MYFA.tasks.length}</span></div>${MYFA.tasks.filter(x=>x.active!==false).map(t=>{const done=(MYFA.user.claimedTasks||[]).includes(String(t.id));return card(`<div class="section-title"><h3>${esc(t.title)}</h3><span class="pill">+${Number(t.reward||0)} 💎</span></div><p class="muted">${esc(t.description||'Complete this task.')}</p>${t.url?`<button class="btn dark" onclick="openTask('${esc(t.url)}')">Open task</button>`:''}<button class="btn green" onclick="claimTask('${esc(t.id)}')" ${done?'disabled':''}>${done?'✅ Claimed':'Claim reward'}</button>`) }).join('')||card('<div class="muted">No active tasks.</div>')}`}
function gamesPage(){return `<div class="section-title"><h2>Games</h2><span class="pill">5 games</span></div>${card(`<h3>✈️ Aviator</h3><p class="muted">Stake gems and target a multiplier. The server creates the crash point.</p><input id="aviStake" class="field" type="number" min="1" value="10"><input id="aviTarget" class="field" type="number" step="0.01" min="1.01" value="1.50"><button class="btn" onclick="playAviator()">Fly & Cash Out</button>`)}${card(`<h3>💎 Drop</h3><p class="muted">Tap gems and avoid bombs for 10 seconds.</p><div id="dropBoard" class="game-board"><div id="dropScore" class="big-number">0</div></div><button class="btn green" onclick="startDropGame()">Start Drop</button>`)}${card(`<h3>🐂 Multi Ox</h3><p class="muted">Pick an ox. One result is drawn by the server.</p><div class="grid grid3">${['A','B','C','D','E'].map(x=>`<button class="btn" onclick="playOx('${x}')">Ox ${x}</button>`).join('')}</div>`)}${card(`<h3>✏️ Sketch Guess</h3><p class="muted">Guess what the server selected.</p><div class="grid">${['cat','car','house','tree','phone'].map(x=>`<button class="btn dark" onclick="playSketch('${x}')">${x}</button>`).join('')}</div>`)}${card(`<h3>🎯 Daily Combo</h3><p class="muted">Select exactly 3 symbols.</p><div id="comboPick" class="grid grid3">${['💎','⭐','🔥','🍀','🎁'].map(s=>`<button class="btn dark" data-combo="${s}" onclick="toggleCombo(this,'${s}')">${s}</button>`).join('')}</div><button class="btn gold" onclick="playCombo()">Try Combo</button>`)} `}
function withdrawPage(){return `<div class="section-title"><h2>Withdraw</h2><span class="pill">$${cash(MYFA.user.realBalance)}</span></div>${card(`<p class="muted">Minimum: $${cash(MYFA.config.minWithdraw||1)}</p><input id="wdAmount" class="field" type="number" step="0.01" placeholder="Amount"><select id="wdMethod" class="field"><option>Telebirr</option><option>CBE Birr</option><option>Bank</option><option>Crypto</option></select><input id="wdAccount" class="field" placeholder="Account / wallet"><button class="btn green" onclick="submitWithdrawal()">Submit Withdrawal</button>`)}${card(`<div class="section-title"><h3>My withdrawals</h3><button class="btn dark" style="width:auto" onclick="refreshWithdrawals()">Refresh</button></div><div id="withdrawList"><div class="muted">Loading...</div></div>`)}`}
function morePage(){const u=MYFA.user||{};const ref='https://t.me/MYFA_BIRR_BOT?start=ref'+(u.telegramId||tg?.initDataUnsafe?.user?.id||'');return `<div class="section-title"><h2>More</h2><span class="pill">MYFA</span></div>${card(`<h3>👥 Invite & Earn</h3><p class="muted">Share this link with friends.</p><input id="refLink" class="field" readonly value="${esc(ref)}"><button class="btn" onclick="copyReferral()">Copy link</button><p class="muted" style="margin-top:8px">Referrer: ${esc(u.referredBy||'None')}</p>`)}${card(`<h3>📺 Ad campaigns</h3><p class="muted">Daily limit: ${Number(MYFA.config.adsDailyLimit||10)}</p>${MYFA.campaigns.slice(0,12).map(a=>`<div class="list-item"><span>${esc(a.title)}<br><small class="muted">+${a.reward} 💎</small></span><button class="btn green" style="width:auto" onclick="watchAd('${esc(a.id)}','${esc(a.url)}')">Watch</button></div>`).join('')||'<div class="muted">No campaigns available.</div>'}`)}${card(`<h3>📊 Leaderboard</h3>${MYFA.leaderboard.map((x,i)=>`<div class="list-item"><span>#${i+1} ${esc(x.name)}</span><b>${Math.floor(x.points||0).toLocaleString()} 💎</b></div>`).join('')||'<div class="muted">No leaderboard data.</div>'}`)}${card(`<h3>⚙️ Settings</h3><select id="lang" class="field"><option value="EN">English</option><option value="AM">አማርኛ</option></select><select id="theme" class="field"><option value="dark">Dark</option><option value="light">Light</option></select><button class="btn" onclick="saveUserSettings()">Save settings</button>`)}${card(`<h3>❓ How to earn</h3><p class="muted">Open Tasks, complete available actions, watch configured ads, play games within the daily limit, invite friends and request withdrawals when your cash balance meets the minimum.</p>`)}${u.isAdmin?adminPanel():''}`}
function adminPanel(){return card(`<h3>🛠 Admin Center</h3><input id="adminUid" class="field" placeholder="User Telegram ID"><div class="grid"><button class="btn red" onclick="setBan(true)">Ban</button><button class="btn dark" onclick="setBan(false)">Unban</button></div><input id="adminWd" class="field" placeholder="Withdrawal ID"><select id="adminStatus" class="field"><option>approved</option><option>rejected</option><option>paid</option></select><button class="btn gold" onclick="reviewWd()">Review withdrawal</button><input id="taskTitle" class="field" placeholder="Task title"><input id="taskDesc" class="field" placeholder="Task description"><input id="taskReward" class="field" type="number" placeholder="Reward gems"><input id="taskUrl" class="field" placeholder="Task URL"><button class="btn" onclick="adminCreateTask()">Create task</button><input id="promoCode" class="field" placeholder="Promo code"><input id="promoReward" class="field" type="number" placeholder="Promo reward"><button class="btn green" onclick="adminPromo()">Create promo</button><button class="btn dark" onclick="adminStats()">Load admin stats</button><div id="adminStats" class="muted"></div>`)}
function render(){const c=$('#content');if(!c)return;if(MYFA.page==='home')c.innerHTML=home();else if(MYFA.page==='tasks')c.innerHTML=tasksPage();else if(MYFA.page==='games')c.innerHTML=gamesPage();else if(MYFA.page==='withdraw')c.innerHTML=withdrawPage();else c.innerHTML=morePage();setHeader();if(MYFA.page==='withdraw')setTimeout(refreshWithdrawals,0)}
async function boot(){try{const d=await call('bootstrap');MYFA.user=d.user;MYFA.config=d.config||{};MYFA.tasks=d.tasks||[];MYFA.campaigns=d.campaigns||[];MYFA.leaderboard=d.leaderboard||[];render()}catch(e){console.error(e);$('#content').innerHTML=card(`<h2>MYFA BIRR</h2><p class="bad">${esc(e.message)}</p><button class="btn" onclick="location.reload()">Reload</button>`)}}
async function reloadData(){const d=await call('bootstrap');MYFA.user=d.user;MYFA.config=d.config||{};MYFA.tasks=d.tasks||[];MYFA.campaigns=d.campaigns||[];MYFA.leaderboard=d.leaderboard||[];render()}
async function claimDaily(){try{const d=await call('daily-claim');MYFA.user=d.user;toast('+'+d.reward+' 💎 daily reward');render()}catch(e){toast(e.message)}}
async function claimTask(id){try{const d=await call('claim-task',{taskId:id});MYFA.user=d.user;toast('Task +'+d.reward+' 💎');render()}catch(e){toast(e.message)}}
function openTask(url){window.open(url,'_blank','noopener,noreferrer')}
async function playAviator(){try{const d=await call('game',{game:'aviator',stake:Number($('#aviStake').value),target:Number($('#aviTarget').value)});MYFA.user=d.user;toast(d.result.win?'🎉 +'+d.result.payout+' 💎':'💥 Crash '+d.result.crash+'x');render()}catch(e){toast(e.message)}}
let dropInterval=null,dropScore=0;function startDropGame(){clearInterval(dropInterval);dropScore=0;const b=$('#dropBoard'),s=$('#dropScore');if(!b)return;s.textContent='0';const until=Date.now()+10000;dropInterval=setInterval(()=>{if(Date.now()>=until){clearInterval(dropInterval);call('game',{game:'drop',score:dropScore}).then(d=>{MYFA.user=d.user;toast('Drop +'+d.result.reward+' 💎');render()}).catch(e=>toast(e.message));return}const e=document.createElement('div');e.className='falling';e.textContent=Math.random()<.16?'💣':'💎';e.style.left=(10+Math.random()*80)+'%';e.style.top=(15+Math.random()*70)+'%';e.onclick=()=>{dropScore=e.textContent==='💣'?Math.max(0,dropScore-20):dropScore+10;s.textContent=dropScore;e.remove()};b.appendChild(e);setTimeout(()=>e.remove(),550)},350)}
async function playOx(pick){try{const d=await call('game',{game:'multi-ox',pick});MYFA.user=d.user;toast(d.result.win?'🐂 Winner +'+d.result.reward+' 💎':'Ox '+d.result.draw);render()}catch(e){toast(e.message)}}
async function playSketch(a){try{const d=await call('game',{game:'sketch',answer:a});MYFA.user=d.user;toast(d.result.win?'✏️ Correct +'+d.result.reward+' 💎':'Answer: '+d.result.answer);render()}catch(e){toast(e.message)}}
function toggleCombo(el,s){if(el.classList.contains('active')){el.classList.remove('active');MYFA.combo=MYFA.combo.filter(x=>x!==s)}else if(MYFA.combo.length<3){el.classList.add('active');MYFA.combo.push(s)}}
async function playCombo(){try{if(MYFA.combo.length!==3)return toast('Select 3 symbols');const d=await call('game',{game:'daily-combo',combo:MYFA.combo});MYFA.user=d.user;toast(d.result.win?'🎯 +'+d.result.reward+' 💎':'Combo: '+d.result.combo.join(' '));MYFA.combo=[];render()}catch(e){toast(e.message)}}
async function submitWithdrawal(){try{const d=await call('withdraw-create',{amount:Number($('#wdAmount').value),method:$('#wdMethod').value,account:$('#wdAccount').value});MYFA.user=d.user;toast('Withdrawal submitted');render()}catch(e){toast(e.message)}}
async function refreshWithdrawals(){try{const d=await call('withdrawals');const el=$('#withdrawList');if(!el)return;el.innerHTML=d.withdrawals.map(w=>`<div class="list-item"><span>${esc(w.method)}<br><small class="muted">${esc(w.id)}</small></span><b>$${cash(w.amount)} · ${esc(w.status)}</b></div>`).join('')||'<div class="muted">No requests.</div>'}catch(e){toast(e.message)}}
async function watchAd(id,url){try{window.open(url||'#','_blank','noopener,noreferrer');await call('ad-open',{adId:id});toast('Watch the ad for 5 seconds...');setTimeout(async()=>{try{const d=await call('claim-ad',{adId:id});MYFA.user=d.user;toast('Ad +'+d.reward+' 💎');render()}catch(e){toast(e.message)}},5200)}catch(e){toast(e.message)}}
function copyReferral(){const x=$('#refLink');navigator.clipboard?.writeText(x.value);toast('Referral link copied')}
async function saveUserSettings(){try{const d=await call('save-settings',{lang:$('#lang').value,theme:$('#theme').value,sound:true});MYFA.user=d.user;document.body.classList.toggle('light',$('#theme').value==='light');toast('Settings saved')}catch(e){toast(e.message)}}
async function createAd(){try{const d=await call('create-ad',{title:$('#adTitle').value,url:$('#adUrl').value,reward:Number($('#adReward').value),budget:Number($('#adBudget').value)});MYFA.user=d.user;toast('Campaign created');await reloadData()}catch(e){toast(e.message)}}
async function setBan(b){try{await call('admin-ban',{telegramId:$('#adminUid').value,banned:b});toast(b?'User banned':'User unbanned')}catch(e){toast(e.message)}}
async function reviewWd(){try{await call('admin-withdraw',{id:$('#adminWd').value,status:$('#adminStatus').value});toast('Withdrawal updated')}catch(e){toast(e.message)}}
async function adminCreateTask(){try{const d=await call('create-task',{title:$('#taskTitle').value,description:$('#taskDesc').value,reward:Number($('#taskReward').value),url:$('#taskUrl').value});MYFA.tasks=d.tasks||MYFA.tasks;toast('Task created');render()}catch(e){toast(e.message)}}
async function adminPromo(){try{const d=await call('admin-promo',{code:$('#promoCode').value,reward:Number($('#promoReward').value)});toast('Promo '+d.code+' created')}catch(e){toast(e.message)}}
async function adminStats(){try{const d=await call('admin-stats');$('#adminStats').textContent='Users: '+d.totalUsers+' · Pending withdrawals: '+d.pendingWithdrawals+' · Tasks: '+d.tasks+' · Campaigns: '+d.campaigns}catch(e){toast(e.message)}}
window.nav=nav;window.claimDaily=claimDaily;window.claimTask=claimTask;window.playAviator=playAviator;window.startDropGame=startDropGame;window.playOx=playOx;window.playSketch=playSketch;window.toggleCombo=toggleCombo;window.playCombo=playCombo;window.submitWithdrawal=submitWithdrawal;window.refreshWithdrawals=refreshWithdrawals;window.watchAd=watchAd;window.copyReferral=copyReferral;window.saveUserSettings=saveUserSettings;window.createAd=createAd;window.setBan=setBan;window.reviewWd=reviewWd;window.adminCreateTask=adminCreateTask;window.adminPromo=adminPromo;window.adminStats=adminStats;window.openTask=openTask;window.closeModal=()=>$('#modal')?.classList.add('hidden');
document.addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(b)nav(b.dataset.nav)});if(tg){tg.ready();tg.expand();try{tg.setHeaderColor('#0a0a1f');tg.setBackgroundColor('#090b18')}catch(e){}}boot();
